x = input('Digite algo no teclado:')
print(f'Esse algo digitado: {x} é qual tipo primitivo?', type(x))
print(f'Esse algo digitado: {x} é um Numerico?',x.isnumeric())
print(f'Esse algo digitado: {x} é alfabético?',x.isalpha())
print(f'Esse algo digitado: {x} é alfanumerico?',x.isalnum())
print(f'Esse algo digitado: {x} esta em letra maiscula?',x.isupper())
print(f'Esse algo digitado: {x} esta em letra? minuscula',x.islower())
print(f'Esse algo digitado: {x} esta em decimal?',x.isdecimal())
print(f'Esse algo digitado: {x} Só tem espaços?',x.isspace())
print(f'Esse algo digitado: {x} Esta capitalizada?',x.istitle())